name: aveonotificationtest
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  aveonotification:
    path: aveonotification

dev_dependencies:
  flutter_test:
    sdk: flutter
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
